package org.dynamisai.core;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Immutable output payload generated by DynamisAiEngine for one tick.
 */
public record AIOutputFrame(
    long tick,
    long elapsedMs,
    Map<EntityId, SteeringOutput> steeringOutputs,
    List<DialogueEvent> dialogueEvents,
    List<AnimationSignal> animationSignals,
    WorldSnapshot worldSnapshot,
    FrameBudgetReport budgetReport
) {
    public boolean hasDialogue() {
        return !dialogueEvents.isEmpty();
    }

    public boolean hasSteering() {
        return !steeringOutputs.isEmpty();
    }

    public Optional<SteeringOutput> steeringFor(EntityId id) {
        return Optional.ofNullable(steeringOutputs.get(id));
    }

    public static AIOutputFrame empty(long tick, long elapsedMs, WorldSnapshot snapshot,
                                      FrameBudgetReport budget) {
        return new AIOutputFrame(
            tick, elapsedMs, Map.of(), List.of(), List.of(), snapshot, budget);
    }
}
